name: SRebirth
version: '1.0'
main: com.spearforge.sRebirth.SRebirth
api-version: '1.16'
authors: [ xenrive ]
description: Island Advertise plugin for Spear Network
website: www.spearnw.com
depend: [PlaceholderAPI]
commands:
  rebirth:
    description: Rebirth plugin commands
    usage: /rebirth
    aliases: [rb]
  arebirth:
    description: Admin commands for managing rebirth levels and points
    usage: /arebirth <subcommand>